### ISSUE TITLE
Upgrade package to be .net standard 2.0 compliant

### ISSUE THREAD

**Issue by AlexRozen** [UnstableMutex/RUPropisNumber#1]
Version for .net standard 2.0 is needed! I have made some refactoring for my own usage, but new nuget package would be nice.
[0001-Upgrade-to-.net-standard-2.0-and-projects-to-SDK-sty.patch](https://github.com/UnstableMutex/RUPropisNumber/files/14361019/0001-Upgrade-to-.net-standard-2.0-and-projects-to-SDK-sty.patch)

**Comment by UnstableMutex** [comment]
commited net core version. for now there is some problems with auth on nuget.org, need some time to solve...

**Comment by AlexRozen** [comment]
Quickly checked the changes,
1. Reference to _MSTest.TestFramework_ package from _RUPropisNumber.csproj_ seems to be redundand.
2. Namespace _RUPropisNumber.Implementations_ seems to need to be corrected to _RuPropisNumber.Implementations_ in _EUR.cs_, _RUB.cs_, _USD.cs_
3. Version for .net standard 2.0 is highly needed.  (but I'm not sure about the exact meaning of _\<GenerateTargetFrameworkAttribute>false\</GenerateTargetFrameworkAttribute>_ project property)

**Comment by UnstableMutex** [comment]
now has to be ok, changed target to netcore 3.1
need some changes in csproj for nuget package,

**Comment by AlexRozen** [comment]
> changed target to netcore 3.1

We have to maintain class library, that is used used both with new .net 6 projects and some legacy .net framework code.
.net core 3.1 target is not great idea in this case :(
I have recompiled your previous fix with .net standard 2.0 target. Only some portions of modern C# sugar had to be changed.

**Comment by UnstableMutex** [comment]
project compiled with net6 without any changes in code files. checked just now. changed only taget platform in csproj file.
probably in nuget package i add support of net6.0

**Comment by AlexRozen** [comment]
We need support of both .net core and .net framework. Ideally from one nuget package. .net standard 2.0 is perfect target for that.

**Comment by UnstableMutex** [comment]
check now uploaded package for 4 targets  old net, 60 and netcore on nuget. now its validating

**Comment by UnstableMutex** [comment]
Done
